version: "3.9"

services:
  web:
    build: .
    ports:
      # Maps the public port from .env to the container's internal port 10000
      - "${PUBLIC_PORT}:10000"
    env_file:
      - .env
    restart: unless-stopped